server:
  port: 8080

spring:
  application:
    name: invest
  profiles:
    active: dev

wx:
  push:
    token: ${WX_PUSH_TOKEN:AT_2yFMb9NeZh78sKcMrVSRtGAKOen0xOtn}
    template:
      id: ${WX_PUSH_TEMPLATE_ID:12345}
    topic:
      ids: ${WX_PUSH_TOPIC_IDS:12345}

# 其他配置... 